package: media_negotiator
version: 6.1.2
name: Media Negotiator
author: Friends of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/media_negotiator

pages:
    media_manager/media_negotiator:
        title: translate:media_negotiator_title
        perm: media_negotiator[]
        subpages:
            setup:
                title: 'translate:media_negotiator_setup_instructions_title'
                icon: 'rex-icon fa-regular fa-images'
            config:
                title: 'translate:media_negotiator_config_title'
                icon: 'rex-icon fa-cog'
            types:
                title: 'translate:media_negotiator_types_title'
                icon: 'rex-icon fa-tasks'
            icc_fix:
                title: 'translate:media_negotiator_icc_fix_title'
                icon: 'rex-icon fa-magic'

default_config:
    force_imagick: false
    disable_avif: false
    webp_quality: 80
    avif_quality: 60
    ua_fallback: false
    preferred_format: avif

console:
    commands:
        'media:negotiator:warmup': FriendsOfRedaxo\MediaNegotiator\Commands\WarmupCommand

requires:
    redaxo: ^5.18.0
    php:
        version: "^8.1"
    packages:
        media_manager: '^2.17.0'
